#!/bin/bash

VERNUM=$(awk '(/"version"/){vernum = $NF; gsub(/[^0-9^.]/, "", vernum); print vernum}' manifest.json)

mv manifest.json manifest.json.original

zip -r "Duo Strength v$VERNUM - chrome & opera.zip" \
	CHANGELOG.md \
	LICENSE \
	manifest.json \
	options.js \
	options.html \
	duoStrength.js \
	icons \
	background.js \
	images \
	styles \
	defaultOptions.json \
	disabledOptions.json

mv manifest.firefox.json manifest.json
zip -r "Duo Strength v$VERNUM - firefox.zip" \
	CHANGELOG.md \
	LICENSE \
	manifest.json \
	options.js \
	options.html \
	duoStrength.js \
	icons \
	background.js \
	images \
	styles \
	defaultOptions.json \
	disabledOptions.json

mv manifest.json manifest.firefox.json
mv manifest.json.original manifest.json
zip -r "Duo Strength v$VERNUM.zip" \
	CHANGELOG.md \
	LICENSE \
	manifest.json \
	manifest.firefox.json \
	options.js \
	options.html \
	duoStrength.js \
	icons \
	background.js \
	images \
	styles \
	defaultOptions.json \
	disabledOptions.json

